import type { AppRole } from "@/lib/demo-auth";

export type CanonicalRole = Exclude<AppRole, "COORDENADOR" | "GERENTE">;

export type RoleCapability =
  | "PERSONAL"
  | "CENTRAL"
  | "REALTIME_FULL"
  | "REALTIME_QUEUES"
  | "CAPTURE"
  | "CAPTURE_MAPPINGS"
  | "STAFF_COVERAGE"
  | "STAFF_COVERAGE_ADS"
  | "STAFF_COVERAGE_MANAGE"
  | "PERFORMANCE"
  | "EMPLOYEE_MAP"
  | "EMPLOYEE_SENSITIVE"
  | "EMPLOYEE_EDIT"
  | "EMPLOYEE_ROLE_EDIT"
  | "SCHEDULE_VIEW"
  | "SCHEDULE_EDIT"
  | "WORK_HOURS_VIEW"
  | "WORK_HOURS_EDIT"
  | "WORK_HOURS_REQUEST"
  | "PIPELINES"
  | "FEEDBACK_SUBMIT"
  | "FEEDBACK_MANAGE"
  | "BILLING_VIEW"
  | "BILLING_MANAGE"
  | "FINANCE_VIEW"
  | "FINANCE_MANAGE"
  | "ADVANCE_VIEW"
  | "ADVANCE_MANAGE"
  | "EQUIPMENT_VIEW"
  | "EQUIPMENT_MANAGE"
  | "SETTINGS"
  | "USERS_MANAGE"
  | "AUDIT_LOGS"
  | "HIERARCHY_VIEW"
  | "HIERARCHY_MANAGE"
  | "REGISTRATION_APPROVE"
  | "ATTENDANCE_MANAGE"
  | "ATTENDANCE_JUSTIFY";

const roleAliases: Record<string, CanonicalRole> = {
  ADMIN: "ADMIN",
  ADMINISTRADOR: "ADMIN",
  ADMINISTRADORA: "ADMIN",
  "ADMIN CENTRAL": "ADMIN",
  COLLABORATOR: "COLABORADOR",
  COLABORADOR: "COLABORADOR",
  SUPERVISOR: "SUPERVISOR",
  WFM: "WFM",
  QUALITY: "QUALIDADE",
  QUALIDADE: "QUALIDADE",
  HR: "RH",
  RH: "RH",
  FINANCE: "FINANCEIRO",
  FINANCIAL: "FINANCEIRO",
  FINANCEIRO: "FINANCEIRO",
  LOGISTICS_IT: "TI",
  IT: "TI",
  TI: "TI",
  RTA: "RTA",
  POC: "POC",
  MANAGEMENT: "GESTOR",
  GESTOR: "GESTOR",
  COORDENADOR: "GESTOR",
  COORDINATOR: "GESTOR",
  GERENTE: "GESTOR",
  MANAGER: "GESTOR",
  CLIENT: "CLIENT",
  CLIENTE: "CLIENT"
};

const roleCapabilities: Record<CanonicalRole, ReadonlySet<RoleCapability>> = {
  ADMIN: new Set<RoleCapability>(),
  GESTOR: new Set([
    "PERSONAL", "CENTRAL", "REALTIME_FULL", "REALTIME_QUEUES", "CAPTURE", "STAFF_COVERAGE", "STAFF_COVERAGE_ADS",
    "STAFF_COVERAGE_MANAGE", "PERFORMANCE", "EMPLOYEE_MAP", "EMPLOYEE_EDIT", "SCHEDULE_VIEW", "WORK_HOURS_VIEW", "WORK_HOURS_EDIT", "PIPELINES",
    "WORK_HOURS_REQUEST", "FEEDBACK_SUBMIT", "ADVANCE_VIEW", "EQUIPMENT_VIEW", "EQUIPMENT_MANAGE", "AUDIT_LOGS", "HIERARCHY_VIEW"
  ]),
  SUPERVISOR: new Set([
    "PERSONAL", "CENTRAL", "REALTIME_FULL", "REALTIME_QUEUES", "CAPTURE", "STAFF_COVERAGE", "STAFF_COVERAGE_ADS",
    "EMPLOYEE_MAP", "SCHEDULE_VIEW", "WORK_HOURS_VIEW", "WORK_HOURS_REQUEST", "PIPELINES", "FEEDBACK_SUBMIT",
    "BILLING_VIEW", "ATTENDANCE_JUSTIFY"
  ]),
  COLABORADOR: new Set(["PERSONAL", "FEEDBACK_SUBMIT", "ADVANCE_VIEW"]),
  WFM: new Set([
    "PERSONAL", "CENTRAL", "REALTIME_FULL", "REALTIME_QUEUES", "CAPTURE", "STAFF_COVERAGE", "STAFF_COVERAGE_ADS",
    "STAFF_COVERAGE_MANAGE", "PERFORMANCE", "EMPLOYEE_MAP", "EMPLOYEE_SENSITIVE", "EMPLOYEE_EDIT", "SCHEDULE_VIEW",
    "SCHEDULE_EDIT", "WORK_HOURS_VIEW", "WORK_HOURS_EDIT", "WORK_HOURS_REQUEST", "PIPELINES", "FEEDBACK_SUBMIT",
    "HIERARCHY_VIEW", "HIERARCHY_MANAGE", "REGISTRATION_APPROVE", "ATTENDANCE_MANAGE", "ATTENDANCE_JUSTIFY"
  ]),
  QUALIDADE: new Set(["PERSONAL", "PERFORMANCE", "SCHEDULE_VIEW", "FEEDBACK_SUBMIT"]),
  RH: new Set([
    "PERSONAL", "CENTRAL", "REALTIME_FULL", "REALTIME_QUEUES", "CAPTURE", "STAFF_COVERAGE", "STAFF_COVERAGE_ADS",
    "PERFORMANCE", "EMPLOYEE_MAP", "EMPLOYEE_SENSITIVE", "EMPLOYEE_EDIT", "SCHEDULE_VIEW",
    "WORK_HOURS_VIEW", "WORK_HOURS_EDIT", "WORK_HOURS_REQUEST", "PIPELINES", "FEEDBACK_SUBMIT", "FEEDBACK_MANAGE",
    "BILLING_VIEW", "FINANCE_VIEW", "ADVANCE_VIEW", "EQUIPMENT_VIEW",
    "EQUIPMENT_MANAGE", "AUDIT_LOGS", "HIERARCHY_VIEW", "HIERARCHY_MANAGE", "REGISTRATION_APPROVE"
  ]),
  FINANCEIRO: new Set([
    "PERSONAL", "CENTRAL", "REALTIME_FULL", "REALTIME_QUEUES", "CAPTURE", "STAFF_COVERAGE", "STAFF_COVERAGE_ADS",
    "PERFORMANCE", "EMPLOYEE_MAP", "EMPLOYEE_SENSITIVE", "EMPLOYEE_EDIT", "SCHEDULE_VIEW",
    "WORK_HOURS_VIEW", "WORK_HOURS_EDIT", "WORK_HOURS_REQUEST", "PIPELINES", "FEEDBACK_SUBMIT", "FEEDBACK_MANAGE",
    "BILLING_VIEW", "FINANCE_VIEW", "ADVANCE_VIEW", "EQUIPMENT_VIEW",
    "EQUIPMENT_MANAGE", "AUDIT_LOGS", "HIERARCHY_VIEW", "HIERARCHY_MANAGE", "REGISTRATION_APPROVE"
  ]),
  TI: new Set(["PERSONAL", "CAPTURE", "EQUIPMENT_VIEW", "EQUIPMENT_MANAGE", "FEEDBACK_SUBMIT"]),
  RTA: new Set(["PERSONAL", "REALTIME_FULL", "REALTIME_QUEUES", "CAPTURE", "STAFF_COVERAGE", "STAFF_COVERAGE_ADS", "FEEDBACK_SUBMIT"]),
  POC: new Set(["PERSONAL", "REALTIME_FULL", "REALTIME_QUEUES", "CAPTURE", "STAFF_COVERAGE", "STAFF_COVERAGE_ADS", "FEEDBACK_SUBMIT"]),
  CLIENT: new Set(["REALTIME_QUEUES", "STAFF_COVERAGE", "PERFORMANCE"])
};

export const allAppRoles: AppRole[] = [
  "ADMIN", "GESTOR", "SUPERVISOR", "COLABORADOR", "WFM", "QUALIDADE", "RH", "FINANCEIRO",
  "TI", "RTA", "POC", "COORDENADOR", "GERENTE", "CLIENT"
];

export function normalizeAccessRole(role?: string | null): CanonicalRole {
  return roleAliases[String(role ?? "COLABORADOR").trim().toUpperCase()] ?? "COLABORADOR";
}

export function roleHasCapability(role: string | null | undefined, capability: RoleCapability) {
  const normalizedRole = normalizeAccessRole(role);
  return normalizedRole === "ADMIN" || roleCapabilities[normalizedRole].has(capability);
}

export function rolesWithCapability(capability: RoleCapability): AppRole[] {
  return allAppRoles.filter((role) => roleHasCapability(role, capability));
}
