export type QueueReportLob = "ADS" | "VIDEO" | "COMMENTS" | "N/A";

export type QueueReportMetadata = {
  queueName: string;
  department: string;
  lob: QueueReportLob;
};

export const QUEUE_REPORT_METADATA: Record<string, QueueReportMetadata> = {
  "2538": {"queueName":"Ug First Moderation Ug Br Default","department":"Ug","lob":"COMMENTS"},
  "3701": {"queueName":"Ug First Moderation Ug Br Default","department":"Ug First Moderation Ug Br Default","lob":"COMMENTS"},
  "3922": {"queueName":"Commercialization Advertiser Verification Brazil Initial","department":"Account Verification","lob":"ADS"},
  "4114": {"queueName":"Commercialization Advertiser Verification Singapore Initial","department":"Account Verification","lob":"ADS"},
  "4115": {"queueName":"Commercialization Advertiser Verification China Initial","department":"Account Verification","lob":"ADS"},
  "4116": {"queueName":"Commercialization Qualification Verification Hong Kong Barrel Initial","department":"Account Verification","lob":"ADS"},
  "4117": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "4118": {"queueName":"Commercialization Advertiser Verification America Initial","department":"Account Verification","lob":"ADS"},
  "5121": {"queueName":"Family Audit Br First Category","department":"Family (Cmc)","lob":"COMMENTS"},
  "5130": {"queueName":"Family Audit Br First Category","department":"Family Audit Br Edit","lob":"COMMENTS"},
  "5486": {"queueName":"Text&Pics Push Labeling Moderation Brazil Initial","department":"Brazil Push","lob":"VIDEO"},
  "5487": {"queueName":"Text&Pics Push Labeling Moderation Brazil Activity Hot Spot","department":"Brazil Push","lob":"VIDEO"},
  "5653": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "5654": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "5655": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "5860": {"queueName":"Safety Second Instance Brazil Language","department":"Brazil Safety","lob":"VIDEO"},
  "6247": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "6375": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "6376": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "6992": {"queueName":"Text&Pics Push Labeling Moderation Brazil Top","department":"Brazil Push","lob":"VIDEO"},
  "7338": {"queueName":"Video Appeal First Trial Brazilian Barrel Language","department":"Brazil Video Appeal","lob":"VIDEO"},
  "7587": {"queueName":"Commercialization Material Report Brazil Initial","department":"Other Queue","lob":"ADS"},
  "7589": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "7590": {"queueName":"Commercialization Material Report Colombia Initial","department":"Other Queue","lob":"ADS"},
  "7591": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "7592": {"queueName":"Commercialization Material Report Universal Initial","department":"Other Queue","lob":"ADS"},
  "7694": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "7696": {"queueName":"Commercialization Advertisement Group Complaint Mexico Initial","department":"Other Queue","lob":"ADS"},
  "7697": {"queueName":"Commercialization Advertisement Group Complaint Colombia Initial","department":"Other Queue","lob":"ADS"},
  "7698": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "7699": {"queueName":"Commercialization Advertisement Group Complaint Universal Initial","department":"Other Queue","lob":"ADS"},
  "7703": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "7716": {"queueName":"Commercialization Dpa Goods Default","department":"Other Queue","lob":"ADS"},
  "7963": {"queueName":"Commercialization Effective Advertising Unit Brazil Initial","department":"效果广告unit 巴西桶(7963)","lob":"ADS"},
  "7965": {"queueName":"Commercialization Effective Advertising Unit Mexico Initial","department":"Other Queue","lob":"ADS"},
  "7966": {"queueName":"Commercialization Effective Advertising Unit Columbia Barrel Initial","department":"Other Queue","lob":"ADS"},
  "7967": {"queueName":"Commercialization Effective Advertising Unit Argentine Barrel Initial","department":"Other Queue","lob":"ADS"},
  "7968": {"queueName":"Commercialization Effective Advertising Unit Universal Initial","department":"Other Queue","lob":"ADS"},
  "8571": {"queueName":"Picture And Text Push Label Review Brazilian Barrel Recall","department":"Brazil Push","lob":"VIDEO"},
  "8572": {"queueName":"Picture And Text Push Label Review Brazilian Barrel Repeat","department":"Brazil Push","lob":"VIDEO"},
  "8587": {"queueName":"Commercialization Open Screen Advertising Brazil Initial","department":"Other Queue","lob":"ADS"},
  "8593": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "8594": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "8595": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "8788": {"queueName":"Commercialization Open Screen Advertising Unit Brazil Initial","department":"Other Queue","lob":"ADS"},
  "8791": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "8792": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "8793": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "8797": {"queueName":"Commercialization Contract Information Flow Unit Brazil Initial","department":"Other Queue","lob":"ADS"},
  "8813": {"queueName":"Commercialization Effect Recall Brazil High Fever","department":"效果召回 巴西桶(8813)","lob":"ADS"},
  "8815": {"queueName":"Commercialization Effect Recall Argentina High Fever","department":"Other Queue","lob":"ADS"},
  "8816": {"queueName":"Commercialization Effect Recall Mexico High Fever","department":"Other Queue","lob":"ADS"},
  "8817": {"queueName":"Commercialization Effect Recall Colombia High Fever","department":"Other Queue","lob":"ADS"},
  "8831": {"queueName":"Commercialization Effect Recall Universal High Fever","department":"Other Queue","lob":"ADS"},
  "9037": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "9038": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "9045": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "9046": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "9049": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "9050": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "9093": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "9105": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "9115": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "9124": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "9550": {"queueName":"Video Report Brazil Reported Many Times","department":"Brazil Video Report","lob":"VIDEO"},
  "9551": {"queueName":"Video Report Brazil Reported Many Times","department":"Brazil Video Report","lob":"VIDEO"},
  "9553": {"queueName":"Video Report Brazil Reported Many Times","department":"Brazil Video Report","lob":"VIDEO"},
  "9596": {"queueName":"Commercial Effect Ad Brazil Original","department":"Effective Ads Org Brazil","lob":"ADS"},
  "9599": {"queueName":"Commercialization Effective Advertising Brazil Top Customers","department":"Other Queue","lob":"ADS"},
  "9607": {"queueName":"Commercialization Effective Advertising Mexico Initial","department":"Other Queue","lob":"ADS"},
  "9610": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "9612": {"queueName":"Commercialization Effective Advertising Columbia Barrel Initial","department":"Other Queue","lob":"ADS"},
  "9615": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "9618": {"queueName":"Commercialization Effective Advertising Argentine Barrel Initial","department":"Other Queue","lob":"ADS"},
  "9621": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "9623": {"queueName":"Commercialization Effective Advertising Universal Initial","department":"Other Queue","lob":"ADS"},
  "9626": {"queueName":"Commercialization Effective Advertising Universal Top Customerss","department":"Other Queue","lob":"ADS"},
  "9643": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "9684": {"queueName":"Commercialization Contract Information Flow Brazil Initial","department":"Other Queue","lob":"ADS"},
  "9687": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "9688": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "9691": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "9692": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "9693": {"queueName":"Commercialization Material Complaint Brazil Initial","department":"Other Queue","lob":"ADS"},
  "9695": {"queueName":"Commercialization Material Complaint Mexico Initial","department":"Other Queue","lob":"ADS"},
  "9696": {"queueName":"Commercialization Material Complaint Colombia Initial","department":"Other Queue","lob":"ADS"},
  "9697": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "9698": {"queueName":"Commercialization Material Complaint Universal Initial","department":"Other Queue","lob":"ADS"},
  "9702": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "9704": {"queueName":"Commercialization Effect Recall Brazil Label","department":"Other Queue","lob":"ADS"},
  "9840": {"queueName":"Commercialization Inspection Brazil Inconsistency","department":"Other Queue","lob":"ADS"},
  "9842": {"queueName":"Commercialization Inspection Mexico Inconsistency","department":"Other Queue","lob":"ADS"},
  "9843": {"queueName":"Commercialization Inspection Colombia Inconsistency","department":"Other Queue","lob":"ADS"},
  "9844": {"queueName":"Commercialization Inspection Argentina Inconsistency","department":"Other Queue","lob":"ADS"},
  "9845": {"queueName":"Commercialization Inspection Universal Inconsistency","department":"Other Queue","lob":"ADS"},
  "9849": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "10215": {"queueName":"Commercialization Recall Brazil Market Label","department":"Other Queue","lob":"ADS"},
  "10801": {"queueName":"Commercialization Advertiser Verification Brazil No Industry","department":"Account Verification","lob":"ADS"},
  "10802": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "10803": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "10804": {"queueName":"Commercialization Advertiser Verification Hong Kong No Industry","department":"Account Verification","lob":"ADS"},
  "10805": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "10806": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "10808": {"queueName":"Commercialization Advertiser Verification Mexico No Industry","department":"Account Verification","lob":"ADS"},
  "10809": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "10810": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "10811": {"queueName":"Commercialization Effective Advertising Unit Brazil No Industry","department":"Other Queue","lob":"ADS"},
  "10813": {"queueName":"Commercialization Effective Advertising Unit Mexico No Industry","department":"Other Queue","lob":"ADS"},
  "10814": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "10815": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "10816": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "10820": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "10869": {"queueName":"Commercialization Open Screen Adunit Brazil No Industry","department":"Other Queue","lob":"ADS"},
  "10872": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "10873": {"queueName":"Commercialization Open Screen Adunit Colombia No Industry","department":"Other Queue","lob":"ADS"},
  "10874": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "10877": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "10878": {"queueName":"Commercialization Contract Information Flow Unit Brazil No Industry","department":"Other Queue","lob":"ADS"},
  "10881": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "10882": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "10885": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "10886": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "11145": {"queueName":"Commercialization Effect Advertising Brazilian Barrel Aigc","department":"Other Queue","lob":"ADS"},
  "11147": {"queueName":"Commercialization Material Complaint Brazil Aigc","department":"Other Queue","lob":"ADS"},
  "11149": {"queueName":"Commercialization Effect Recall Brazil Aigc","department":"Other Queue","lob":"ADS"},
  "11151": {"queueName":"Commercialization Material Report Brazil Aigc","department":"Other Queue","lob":"ADS"},
  "11239": {"queueName":"Commercialization Landing Page Brazil Initial","department":"Other Queue","lob":"ADS"},
  "11265": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "11266": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "11267": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "11268": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "11272": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "11364": {"queueName":"Video Second Trial Of Security Brazilian Barrel Fc Reply","department":"Brazil Safety","lob":"VIDEO"},
  "11762": {"queueName":"Commercialization Little Bell Brazil Initial","department":"Other Queue","lob":"ADS"},
  "11764": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "11897": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "11898": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "11904": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "11906": {"queueName":"Commercialization Little Bell Xiaodang Tongjue Bucket Initial","department":"Other Queue","lob":"ADS"},
  "11907": {"queueName":"Commercialization Little Bell Brazil No Industry","department":"Other Queue","lob":"ADS"},
  "11909": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "11910": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "11911": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "11915": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "11917": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "12884": {"queueName":"Commercialization Picture Brazil Initial","department":"Other Queue","lob":"ADS"},
  "13169": {"queueName":"Live Slicin Anchor Brazil Kcm Short Slicing","department":"Kcm短切片(13169)","lob":"ADS"},
  "13222": {"queueName":"Commercialization Kwai Video Brazil Initial","department":"Other Queue","lob":"ADS"},
  "13328": {"queueName":"Commercialization Effect Recall Brazil Double Confirmation","department":"Other Queue","lob":"ADS"},
  "13461": {"queueName":"Commercialization Expert Ad Unit Brazil Initial","department":"Other Queue","lob":"ADS"},
  "14198": {"queueName":"Commercialization Recorded&Livevideo Brazil Hybrid","department":"Other Queue","lob":"ADS"},
  "600000615": {"queueName":"Private Letter Report Review Mixed Bucket Default","department":"Private Letter Report Examination Brazilian Barrel Voice Private Letter","lob":"COMMENTS"},
  "600000922": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "600000968": {"queueName":"Private Letter Report Review Mixed Bucket Default","department":"Dm Report","lob":"COMMENTS"},
  "600000970": {"queueName":"Private Letter Report Review Mixed Bucket Default","department":"Private Letter Report Review Brazilian Barrel Default","lob":"COMMENTS"},
  "600001199": {"queueName":"Report Br First Category","department":"Comments Report","lob":"COMMENTS"},
  "600001227": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "600001228": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "600001237": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "600001239": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "600001240": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "600001241": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "600001260": {"queueName":"User Report Review Brazilian Barrel Language","department":"User Report","lob":"VIDEO"},
  "600001275": {"queueName":"User Complaint Brazilian Barrel Initial","department":"User Appeal","lob":"VIDEO"},
  "600001276": {"queueName":"User Complaint Brazilian Barrel Initial","department":"User Complaint Brazil Underage","lob":"VIDEO"},
  "600001295": {"queueName":"Comment Label Review Brazilian Barrel Quality Inspection Queue","department":"Comment Label Review Brazilian Barrel Market Label","lob":"COMMENTS"},
  "600001300": {"queueName":"Comment Label Review Brazilian Barrel Quality Inspection Queue","department":"Text Annotation Of Private Messages","lob":"COMMENTS"},
  "600001305": {"queueName":"Comment Label Review Brazilian Barrel Quality Inspection Queue","department":"Comment Label Review Brazilian Barrel Market Label","lob":"COMMENTS"},
  "600001306": {"queueName":"Comment Label Review Brazilian Barrel Quality Inspection Queue","department":"Comment Annotated Review Brazilian Barrel Sensitive Word","lob":"COMMENTS"},
  "600001311": {"queueName":"Comment Label Review Brazilian Barrel Quality Inspection Queue","department":"Comment Label Review Brazilian Barrel Image Comment Check","lob":"COMMENTS"},
  "600001312": {"queueName":"Comment Label Review Brazilian Barrel Quality Inspection Queue","department":"Comment Label Review Brazilian Barrel Expert Quality Inspection Queue","lob":"COMMENTS"},
  "600001317": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "600001322": {"queueName":"Fila não mapeada","department":"Other Queue","lob":"N/A"},
  "600001428": {"queueName":"Picture And Text Push Label Review Brazilian Barrel Hot Spot","department":"Brazil Push","lob":"VIDEO"},
  "600001812": {"queueName":"Push Copy Review Brazilian Barrel Emergency Hot Spot","department":"Brazil Push","lob":"VIDEO"},
  "600002377": {"queueName":"Private Letter Picture Annotation","department":"Text Annotation Of Private Messages","lob":"COMMENTS"},
  "600002381": {"queueName":"Private Letter Picture Annotation","department":"Pm Tagging","lob":"COMMENTS"},
};

export function getQueueReportMetadataById(queueId?: string | null): QueueReportMetadata {
  const normalizedQueueId = String(queueId ?? "").trim();
  if (normalizedQueueId && QUEUE_REPORT_METADATA[normalizedQueueId]) return QUEUE_REPORT_METADATA[normalizedQueueId];
  return { queueName: "Fila não mapeada", department: "Other Queue", lob: "N/A" };
}
